version: "3.9"

services:
  client:
    container_name: practicum-client
    image: practicum-client
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - awesome
    depends_on:
      - server

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - awesome

  server:
    container_name: prakticum-server
    image: prakticum-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        POSTGRES_HOST: postgres
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT},
      POSTGRES_HOST: postgres
    networks:
      - awesome
    depends_on:
      - postgres
    links:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - awesome
    depends_on:
      - postgres
    links:
      - postgres


volumes:
  pgadmin-data:
  postgresdata:

networks:
  awesome:
    driver: bridge
