export enum Color {
  AliceBlue = 'ALICEBLUE',
  Aqua = 'AQUA',
  Black = '#181818',
  Blue = 'BLUE',
  Brown = 'BROWN',
  Green = 'GREEN',
  Grey = '#636363',
  LightCyan = 'LIGHTCYAN',
  LightGrey = 'LIGHTGREY',
  Lime = 'LIME',
  NormalGrey = 'GREY',
  Orange = 'ORANGE',
  Pink = '#483D8B',
  Red = 'RED',
  Transparent = 'TRANSPARENT',
  White = '#DAD7CD',
  Yellow = 'YELLOW',
}
